chore: Support $(JsonSerializerIsReflectionEnabledByDefault)=false
Context: https://github.com/unoplatform/uno.extensions/pull/2970

Fixes: https://github.com/unoplatform/uno.extensions/issues/2908

When [`$(JsonSerializerIsReflectionEnabledByDefault)`][0]=false,
then various `JsonSerializer` methods will throw.

For example:

	partial class SerializerExtensionsTests {
	  [TestMethod]
	  public void ToFromStringTest()
	  {
	    var services    = new ServiceCollection().BuildServiceProvider();
	    var Serializer  = new SystemTextJsonSerializer(services);
	    var classEntity = new SimpleClass { SimpleTextProperty = SimpleText + "Hello World!Class" };
	    var stringValue = Serializer.ToString(classEntity);
	    // …
	  }
	}

Fails with:

	  Failed ToFromStringTest [< 1 ms]
	  Error Message:
	   Test method Uno.Extensions.Serialization.Tests.SerializerExtensionsTests.ToFromStringTest threw exception:
	System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
	  Stack Trace:
	   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
	   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
	   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
	   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerOptions options)
	   at Uno.Extensions.Serialization.SystemTextJsonSerializer.ToString(Object value, Type valueType) in /Volumes/Xamarin-Work/src/unoplatform/uno.extensions/src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs:line 101
	   at Uno.Extensions.Serialization.SerializerExtensions.ToString[T](ISerializer serializer, T value) in /Volumes/Xamarin-Work/src/unoplatform/uno.extensions/src/Uno.Extensions.Serialization/SerializerExtensions.cs:line 24
	   at Uno.Extensions.Serialization.Tests.SerializerExtensionsTests.ToFromStringTest() in /Volumes/Xamarin-Work/src/unoplatform/uno.extensions/src/Uno.Extensions.Serialization.Tests/StreamSerializerExtensionsTests.cs:line 66
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

The question: how should this work?  How *can* it work?

The [ASP.NET Core support for Native AOT > Changes to support source generation][1]
documentation section provides some ideas for how this can work.

The fundamental point: if Reflection based JSON (de)serialization
cannot be used, and the suggested alternative is to use
[System.Text.Json source generation][2], then there needs to be a way
for the framework to use the generated code.

In the ASP.NET Core docs, they suggest using the
[`HttpJsonServiceExtensions.ConfigureHttpJsonOptions()`][3] extension
method during service configuration:

	var builder = WebApplication.CreateSlimBuilder(args);
	builder.Services.ConfigureHttpJsonOptions(options =>
	{
	  options.SerializerOptions.TypeInfoResolverChain.Insert(0, AppJsonSerializerContext.Default);
	});

	// …

	[JsonSerializable(typeof(Todo[]))]
	internal partial class AppJsonSerializerContext : JsonSerializerContext
	{
	}

In order to work when
`$(JsonSerializerIsReflectionEnabledByDefault)`=false,
Uno.Extensions.Serialization needs a similar mechanism, a way to
provide the generated `JsonSerializerContext` types to
Uno.Extensions.Serialization.

Draw inspiration from ASP.NET Core:

  * https://github.com/dotnet/dotnet/blob/9add30f0238eabacba9a92acec51a8d714fd1881/src/aspnetcore/src/Http/Http.Extensions/src/JsonOptions.cs
  * https://github.com/dotnet/dotnet/blob/9add30f0238eabacba9a92acec51a8d714fd1881/src/aspnetcore/src/Http/Http.Extensions/src/HttpJsonServiceExtensions.cs#L23-L27
  * https://github.com/dotnet/dotnet/blob/9add30f0238eabacba9a92acec51a8d714fd1881/src/aspnetcore/src/Http/Http.Extensions/src/HttpRequestJsonExtensions.cs#L397-L401

The core of the new mechanism *mirrors* what ASP.NET Core does:

	public partial class JsonSerializationOptions {
	  public JsonSerializerOptions SerializerOptions { get; }
	}
	public partial class ServiceCollectionExtensions {
	  public static IServiceCollection ConfigureJsonSerializationOptions(this IServiceCollection services, Action<SerializationOptions> configureOptions);
	  public static IServiceCollection AddJsonSerialization(this IServiceCollection services, HostBuilderContext context);
	  public static IServiceCollection AddJsonSerializationTypeInfoResolvers(this IServiceCollection services, params IEnumerable<IJsonTypeInfoResolver> typeInfoResolvers);
	}
	public partial class HostBuilderExtensions {
	  public static IHostBuilder UseJsonSerializationResolvers(this IHostBuilder hostBuilder, params IJsonTypeInfoResolver[] typeInfoResolvers)
	  public static IHostBuilder UseJsonSerializationResolvers(this IHostBuilder hostBuilder, IEnumerable<IJsonTypeInfoResolver> typeInfoResolvers, Action<IServiceCollection> configure);
	  public static IHostBuilder UseJsonSerializationResolvers(this IHostBuilder hostBuilder, IEnumerable<IJsonTypeInfoResolver> typeInfoResolvers, Action<HostBuilderContext, IServiceCollection>? configure = default);
	}

This allows adding the generated `*SerializationContext.Default`
properties for subsequent use:

	hostBuilder.UseJsonSerializationResolvers(AppJsonSerializerContext.Default);

To lead developers to the new APIs, the existing
`IHostBuilder.UseSerialization()` and
`IServiceCollection.AddSystemTextJsonSerialization()`, extension
methods have been marked with `[RequiresDynamicCode]` and
`[RequiresUnreferencedCode]`, as a way to notify developers of the
new mechanism.

To *test* this, add a new `src/Uno.Extensions.Serialization.AotTests`
test project which:

 1. Sets `$(JsonSerializerIsReflectionEnabledByDefault)`=false, and
 2. Defines `WITH_AOT_TRIMMING`, and
 3. Imports all the C# source from
    `src/Uno.Extensions.Serialization.Tests`.

The `WITH_AOT_TRIMMING` define allows us to use the same set of
serialization tests for both untrimmed and trimmed environments.

Update `stage-build-packages.yml` so that `*.AotTests.dll` are also
executed by `VSTest@2`.

Additionally, enable `$(IsAotCompatible)`=true for:

  * `src/Uno.Extensions.Serialization/Uno.Extensions.Serialization.csproj`

Address the following warnings:

	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(120,14): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.ToString(Object, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.ToString(Object, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(88,16): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.ToString(Object, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.ToString(Object, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(107,17): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.FromString(String, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.FromString(String, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(120,14): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.FromString(String, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.FromString(String, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(43,17): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.FromStream(Stream, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.FromStream(Stream, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(120,14): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.FromStream(Stream, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.FromStream(Stream, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(62,14): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.ToStream(Stream, Object, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.ToStream(Stream, Object, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(120,14): error IL2046:
	  Member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.ToStream(Stream, Object, Type)' with 'RequiresUnreferencedCodeAttribute' implements interface member 'Uno.Extensions.Serialization.ISerializer.ToStream(Stream, Object, Type)' without 'RequiresUnreferencedCodeAttribute'.
	  'RequiresUnreferencedCodeAttribute' annotations must match across all interface implementations or overrides.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(146,10): error IL2026:
	  Using member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.FromStream(Stream, Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  From JsonDeserializer: JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(157,10): error IL2026:
	  Using member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.ToString(Object, Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  From JsonDeserializer: JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(140,10): error IL2026:
	  Using member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.FromString(String, Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  From JsonDeserializer: JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(168,3): error IL2026:
	  Using member 'Uno.Extensions.Serialization.SystemTextJsonSerializer.ToStream(Stream, Object, Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  From JsonDeserializer: JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(46,89): error IL3050:
	  Using member 'System.Text.Json.JsonSerializer.Deserialize(Stream, Type, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(71,4): error IL3050:
	  Using member 'System.Text.Json.JsonSerializer.Serialize(Stream, Object, Type, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(91,85): error IL3050:
	  Using member 'System.Text.Json.JsonSerializer.Serialize(Object, Type, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(110,89): error IL3050:
	  Using member 'System.Text.Json.JsonSerializer.Deserialize(String, Type, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.

Suppress the above warnings.  The foundation logic in
`SystemTextJsonSerializer.cs` has been reworked to check
[`JsonSerializer.IsReflectionEnabledByDefault`][4], which in turn
should mirror the `$(JsonSerializerIsReflectionEnabledByDefault)`
MSBuild property.  This allows us to mirror System.Text.Json default
behavior, attempting Reflection use when
`JsonSerializer.IsReflectionEnabledByDefault` is true, otherwise
throwing an `InvalidOperationException` stating how to address the
problem:

	Reflection-based serialization has been disabled for this application.
	Use the IServiceCollection.AddJsonTypeInfoResolvers() or IHostBuilder.UseSerializationResolvers() extension methods to enable JSON deserialization for type `Example`.

[0]: https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/publishtrimmed
[1]: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/native-aot?view=aspnetcore-10.0#changes-to-support-source-generation
[2]: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation
[3]: https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpjsonserviceextensions.configurehttpjsonoptions?view=aspnetcore-9.0
[4]: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.isreflectionenabledbydefault?view=net-10.0