fix(samples): Fix samples builds
Commit 56a003bab6834a77edcb7d727b8e35315059c06a got
the **Packages** stage passing.

What's failing are building the samples, e.g. from
Build Samples > Samples - Windows (MauiEmbedding) > Build Samples:

	D:\a\1\s\samples\MauiEmbedding\MauiEmbedding\MauiEmbedding.csproj : error NU1605: Warning As Error: Detected package downgrade: Uno.Toolkit.WinUI from 8.2.1 to 7.0.7. Reference the package directly from the project to select a different version.  [D:\a\1\s\samples\MauiEmbedding\MauiEmbedding.sln]
	D:\a\1\s\samples\MauiEmbedding\MauiEmbedding\MauiEmbedding.csproj : error NU1605:  MauiEmbedding -> Uno.UI.HotDesign 1.16.109 -> Uno.Toolkit.WinUI (>= 8.2.1)  [D:\a\1\s\samples\MauiEmbedding\MauiEmbedding.sln]
	D:\a\1\s\samples\MauiEmbedding\MauiEmbedding\MauiEmbedding.csproj : error NU1605:  MauiEmbedding -> Uno.Toolkit.WinUI (>= 7.0.7) [D:\a\1\s\samples\MauiEmbedding\MauiEmbedding.sln]

Where is 7.0.7 coming from?!

7.0.7 is coming from `$(UnoToolkitVersion)`, overridden in
`samples/Directory.Packages.props`.

For now, remove *all* of the `$(Uno*)` MSBuild property overrides.
This means we're no longer forcing use of
`Uno.Toolkit.WinUI.Material/7.0.7` (released 6 months ago) and
instead are using the defaults specified in Uno.Sdk.Private.

Additionally, update other MSBuild properties as required, e.g.
`$(WinAppSdkVersion)`, in order to avoid NuGet errors:

	error NU1605: Warning As Error: Detected package downgrade: Microsoft.WindowsAppSDK from 1.7.250909003 to 1.7.250513003. Reference the package directly from the project to select a different version.

Finally, "Samples - WebAssembly" was failing with:

	Error: Not found SourceFolder: /home/vsts/work/1/s/testing/TestHarness/TestHarness/bin/Release/net9.0-browserwasm/dist

This is because .NET 9 now uses `wwwroot`. Update the copy.