chore: preserve properties on generated ViewModels
Context: https://github.com/unoplatform/uno.extensions/pull/2966

While running the uno.chefs app on macOS under NativeAOT:

	dotnet publish -c Release -r osx-x64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop -bl \
	  Chefs/Chefs.csproj \
	  -p:SelfContained=true -p:PublishAot=true -p:IsAotCompatible=true -p:UseSkiaRendering=true \
	  -p:IlcGenerateMapFile=true -p:IlcGenerateMstatFile=true -p:IlcGenerateDgmlFile=true \
	  -p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath=`pwd`/_gen
	Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs

Console output would contain the following error:

	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [CurrentIndex] property getter does not exist on type [Chefs.Business.Models.BindableIntIteratorViewModel]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The property setter for [CurrentIndex] does not exist on [Chefs.Business.Models.BindableIntIteratorViewModel]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [Value] property getter does not exist on type [Chefs.Business.Models.BindableIntIteratorViewModel]

PR #2966 had a similar set of messages, and the general fix is to use
`[DynamicallyAccessedMembers]` so that NativeAOT preserves property
metadata.

The problem *here* is that there is no good place to put
`[DynamicallyAccessedMembers]` that will preserve the ViewModel types
generated by Uno.Extensions.Reactive.Generator:

	namespace Chefs.Business.Models {
	  [GeneratedCodeAttribute("ViewModelGenerator_2", "2")]
	  [Bindable(typeof(IntIterator))]
	  public partial class BindableIntIteratorViewModel : global::Uno.Extensions.Reactive.Bindings.Bindable<Chefs.Business.Models.IntIterator> {
	    public IntIterator Value {get => …; set => …;}
	    public int CurrentIndex {get => …; set => …;}
	  }
	}
	namespace Chefs.Presentation {
	  [GeneratedCodeAttribute("ViewModelGenTool_3", "3")]
	  [Bindable(typeof(global::Chefs.Presentation.WelcomeModel))]
	  public partial class WelcomeViewModel {
	    protected WelcomeViewModel(global::Chefs.Presentation.WelcomeModel model) {
	      // …
	      Pages ??= new Chefs.Business.Models.BindableIntIteratorViewModel(…);
	      // …
	    }
	    public Chefs.Business.Models.BindableIntIteratorViewModel Pages { get; private set; }
	  }
	}

Nothing tells NativeAOT to preserve the `BindableIntIteratorViewModel`
properties, so they're "removed" from Reflection metadata.

Update `BindableFromFeedProperty.cs` to use `[DynamicDependency]`
on the `WelcomeViewModel.Pages` property accessor:

	namespace Chefs.Presentation {
	  public partial class WelcomeViewModel {
	    public Chefs.Business.Models.BindableIntIteratorViewModel Pages
	    {
	      [DynamicDependency(DynamicallyAccessedMemberTypes.PublicProperties, typeof(Chefs.Business.Models.BindableIntIteratorViewModel))]
	      get;
	      private set;
	    }
	  }
	}

This change informs NativeAOT that if the `WelcomeViewModel.Pages`
property getter is preserved, then the public properties on
`BindableIntIteratorViewModel` should also be made accessible via
Reflection.  This fixes the original message:

	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [CurrentIndex] property getter does not exist on type [Chefs.Business.Models.BindableIntIteratorViewModel]

…only to replace it with this *different* set of failure messages:

	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [CanMovePrevious] property getter does not exist on type [Chefs.Business.Models.IntIterator]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [CanMovePrevious] property getter does not exist on type [Chefs.Business.Models.IntIterator]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [CanMoveNext] property getter does not exist on type [Chefs.Business.Models.IntIterator]
	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [CanMoveNext] property getter does not exist on type [Chefs.Business.Models.IntIterator]

Address this new set of messages by updating `Bindable<T>` to

	partial class Bindable<
	  [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)]
	  T
	> : IBindable
	{
	}

As `BindableIntIteratorViewModel` inherits from `Bindable<IntIterator>`
this causes the public properties on `IntIterator` to be preserved,
fixing the previous set of failure messages.

Adding `[DynamicallyAccessedMembers]` to `Bindable<T>` breaks
`BindableEnumerable<…>`:

	BindableEnumerable.cs(22,23): error IL2091:
	  'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in 'Uno.Extensions.Reactive.Bindings.Bindable<T>'.
	  The generic parameter 'TCollection' of 'Uno.Extensions.Reactive.Bindings.BindableEnumerable<TCollection, TItem, TBindableItem>' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Annotate the `TCollection` type parameter accordingly to fix the error.