chore: Preserve generated `*ViewModel` constructors, properties
Context: https://github.com/unoplatform/uno/commit/559b1f7866028a1d23f74ba43c3e8614a8e9f284

While running the uno.chefs app on macOS under NativeAOT:

	dotnet publish -c Release -r osx-x64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop -bl \
	  Chefs/Chefs.csproj \
	  -p:SelfContained=true -p:PublishAot=true -p:IsAotCompatible=true -p:UseSkiaRendering=true \
	  -p:IlcGenerateMapFile=true -p:IlcGenerateMstatFile=true -p:IlcGenerateDgmlFile=true -p:IlcGenerateMetadataLog=true \
	  -p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath=`pwd`/_gen
	Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs

Console output would contain the following warnings:

	fail: Uno.UI.Dispatching.NativeDispatcher[0]
	      NativeDispatcher unhandled exception
	      System.InvalidOperationException: A suitable constructor for type 'Chefs.Presentation.ShellViewModel' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

With a local patch in `Uno.dll`, we see that the above
`InvalidOperationException` is from
Microsoft.Extensions.DependencyInjection:

	fail: Uno.UI.Dispatching.NativeDispatcher[0]
	      NativeDispatcher unhandled exception
	      System.InvalidOperationException: A suitable constructor for type 'Chefs.Presentation.ShellViewModel' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, ServiceIdentifier, Type, CallSiteChain) + 0x3e9
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateExact(ServiceDescriptor, ServiceIdentifier, CallSiteChain, Int32) + 0x181
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier, CallSiteChain) + 0x14f
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain) + 0xc9
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier, CallSiteChain) + 0x92
	         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier) + 0x68
	         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0xd2
	         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x39
	         at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass8_0.<<CreateViewModel>b__0>d.MoveNext() + 0x80

The problem is that trimming removed the `ShellViewModel` constructor,
along with other members.

Question: why were these members removed?

Answer 1: because the members weren't *used*, via static analysis.
This is the case here, as there is no `new ShellViewModel()` within
`uno.chefs` or its generated code.

Answer 2: Even when "Answer 1" isn't true, the linker *not* removing
a member *doesn't* mean that the member can be accessed through
Reflection!  Reflection requires a different set of data.

We thus need to convince the trimmer to not only preserve the members,
but also to allow the members to be used through Reflection.

From unoplatform/uno@559b1f78:

> The two predominant ways to do this are via the custom attributes:
>
>   * `DynamicallyAccessedMembersAttribute`
>   * `DynamicDependencyAttribute`

At this point we know we have e.g. `ShellModel` (user-written code),
and `ShellViewModel` (from `src/Uno.Extensions.Reactive.Generator`).

How are these types associated with each other at runtime?

They're associated with each other at runtime via a dictionary
generated by `BindableViewModelMappingGenerator`:

	// generated code
	namespace Chefs;
	partial class ReactiveViewModelMappings {
	  public static readonly IDictionary<Type, Type> ViewModelMappings = new Dictionary<Type, Type> {
	    { typeof(ShellModel), typeof(ShellViewModel) },
	    // …
	  };
	}

Use of `IViewRegistry.FindViewByModel<T>()` allows finding the latter
from the former, e.g. `views.FindViewByModel<ShellModel>()` returns a
`MappedViewMap` with `MappedViewMap.MappedViewModel` being
`ShellViewModel`:

	Console.WriteLine(views.FindByViewModel<ShellModel>());
	// MappedViewMap { View = , ViewSelector = , ViewModel = Chefs.Presentation.ShellModel, Data = , ResultData = , ViewAttributes = , MappedViewModel = Chefs.Presentation.ShellViewModel }

To preserve the `ShellViewModel` members, where do we put
`[DynamicallyAccessedMembers]` or `[DynamicDependency]`?

There are two plausible places:

 1. On `ModelAttribute` and `IModel<T>`
 2. Within `BindableViewModelMappingGenerator`-generated code.

(1) `ModelAttribute` and `IModel<T>` are viable locations because
`ViewModelGenTool_*` emits partial types for e.g. `ShellModel`:

	// generated code
	[Model(typeof(ShellViewModel))]
	partial record ShellModel : IModel<ShellViewModel> {
	}

While this works, it also means that using `[Model]`/`IModel<T>`
without MVUX would result in app size increases.

Which leaves (2): update `BindableViewModelMappingGenerator` so that
a codepath uses `[DynamicallyAccessedMembers]`.

Update `BindableViewModelMappingGenerator` to instead emit code
similar to:

	namespace Chefs;
	static partial class ReactiveViewModelMappings
	{
	  private const DynamicallyAccessedMemberTypes Types =
	      DynamicallyAccessedMemberTypes.PublicConstructors
	    | DynamicallyAccessedMemberTypes.PublicProperties
	    ;

	  private static void AddMapping(
	    Dictionary<Type, Type> dict,
	    Type key,
	    [DynamicallyAccessedMembers(Types)] Type value)
	    => dict.Add(key, value);

	  public static readonly IDictionary<Type, Type> ViewModelMappings;

	  static ReactiveViewModelMappings()
	  {
	    var mappings = new Dictionary<Type, Type>();
	    AddMapping(mappings, typeof(Chefs.Presentation.ShellModel), typeof(global::Chefs.Presentation.ShellViewModel));
	    // …
	    ViewModelMappings = mappings;
	  }
	}

The introduction of `ReactiveViewModelMappings.AddMapping()` allows
a place to provide `[DynamicallyAccessedMembers]`, which in turn
allows the trimmer to preserve constructors and properties on
`ShellViewModel`, which fixes the `InvalidOperationException`.

Note that properties must also be preserved, as if only constructors
are preserved we will see this failure message:

	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [Pages] property getter does not exist on type [Chefs.Presentation.WelcomeViewModel]