chore: Preserve ModelAttribute.Bindable constructors, properties
While running the uno.chefs app on macOS under NativeAOT:

	dotnet publish -c Release -r osx-x64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop -bl \
	  Chefs/Chefs.csproj \
	  -p:SelfContained=true -p:PublishAot=true -p:IsAotCompatible=true -p:UseSkiaRendering=true \
	  -p:IlcGenerateMapFile=true -p:IlcGenerateMstatFile=true -p:IlcGenerateDgmlFile=true \
	  -p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath=`pwd`/_gen
	Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs

Console output would contain the following warnings:

	fail: Uno.UI.Dispatching.NativeDispatcher[0]
	      NativeDispatcher unhandled exception
	      System.InvalidOperationException: A suitable constructor for type 'Chefs.Presentation.ShellViewModel' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

With a local patch in `Uno.dll`, we see that the above
`InvalidOperationException` is from
Microsoft.Extensions.DependencyInjection:

	fail: Uno.UI.Dispatching.NativeDispatcher[0]
	      NativeDispatcher unhandled exception
	      System.InvalidOperationException: A suitable constructor for type 'Chefs.Presentation.ShellViewModel' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, ServiceIdentifier, Type, CallSiteChain) + 0x3e9
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateExact(ServiceDescriptor, ServiceIdentifier, CallSiteChain, Int32) + 0x181
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier, CallSiteChain) + 0x14f
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain) + 0xc9
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier, CallSiteChain) + 0x92
	         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier) + 0x68
	         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0xd2
	         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x39
	         at Uno.Extensions.Navigation.Navigators.ControlNavigator.<>c__DisplayClass8_0.<<CreateViewModel>b__0>d.MoveNext() + 0x80

This is actually fixable within uno.extensions!  The `ShellViewModel`
type is referenced by *both* `[Model]` and `IModel<ShelViewModel>`
in generated code:

	// Chefs.Presentation.ShellModel.g.cs
	namespace Chefs.Presentation;
	[Model(typeof(ShellViewModel))]
	partial record ShellModel : IModel<ShellViewModel> {
	}

`ModelAttribute` and `IModel<TViewModel>` thus give us places to tell
NativeAOT to preserve the constructors on `ShellViewModel`.

After having done so, the new failure message appears:

      	fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
	      The [Pages] property getter does not exist on type [Chefs.Presentation.WelcomeViewModel]

This can *also* be fixed by telling NativeAOT to preserve
*properties* as well, as `WelcomeViewModel` goes through similar
infrastructure as `ShellViewModel`.

Update `ModelAttribute` so that the `Type bindable` constructor
parameter preserves both constructors and properties.

Update `IModel<TViewModel>` *for consistency* with `[Model]` to also
preserve constructor and properties on type parameter `TViewModel`.