chore: update Microsoft.Kiota NuGet package versions
Context: 3cc5c235e551c567369a3b2fc5826cb50d63251a
Context: cd3e1a6dc692c6bfaa0c7bacb211e72976e26446
Context: https://github.com/microsoft/kiota-dotnet/commit/a2800ab7c9bfa0292b8490b91962636917fa8c4c
Changes: https://github.com/microsoft/kiota-dotnet/compare/v1.16.4...v1.21.0

	% git diff --shortstat v1.16.4...v1.21.0
	 48 files changed, 1209 insertions(+), 224 deletions(-)

It's our favorite exercise, making uno.chefs run under NativeAOT!

	dotnet publish -c Release -r osx-x64 -f net10.0-desktop -p:TargetFrameworkOverride=net10.0-desktop -bl \
	  Chefs/Chefs.csproj \
	  -p:SelfContained=true -p:PublishAot=true -p:IsAotCompatible=true -p:UseSkiaRendering=true \
	  -p:IlcGenerateMapFile=true -p:IlcGenerateMstatFile=true -p:IlcGenerateDgmlFile=true -p:IlcGenerateMetadataLog=true \
	  -p:EmitCompilerGeneratedFiles=true -p:CompilerGeneratedFilesOutputPath=`pwd`/_gen
	Chefs/bin/Release/net10.0-desktop/osx-x64/publish/Chefs

When running the app with an updated set of `Uno.Extensions.*`
assemblies from commit 3cc5c235, the app log contains:

	fail: Uno.UI.Dispatching.NativeDispatcher[0]
	      NativeDispatcher unhandled exception
	      System.InvalidOperationException: A suitable constructor for type 'Microsoft.Kiota.Http.HttpClientLibrary.Middleware.UriReplacementHandler`1[Microsoft.Kiota.Http.HttpClientLibrary.Middleware.Options.UriReplacementHandlerOption]' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
	         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, ServiceIdentifier, Type, CallSiteChain) + 0x3e9

The hope had been that commit cd3e1a6d, in fixing various
uno.extensions trimmer warnings, would also fix this warning.
That hope turns out to have been wrong.

Thus, the question: why weren't the constructors for
`UriReplacementHandler<TUriReplacementHandlerOption>` being preserved?

Investigation found that `KiotaClientFactory.GetDefaultHandlerTypes()`
returned a list of types:

	partial class KiotaClientFactory {
	    public static IList<Type> GetDefaultHandlerTypes() => [
	        typeof(UriReplacementHandler<UriReplacementHandlerOption>),
	        typeof(RetryHandler),
	        // …
	    ];
	}

As we know from our [NativeAOT+Reflection Primer][0], if code is going
to use `Activator.CreateInstance()`/etc. to instantiate a type, then
"reflection metadata" for the type's constructors must be retained,
which in turn is influenced by `[DynamicallyAccessedMembers]` and/or
`[DynamicDependency]`.

Note that the above *does not use* `[DynamicallyAccessedMembers]`.

Fortunately, this problem was addressed in
microsoft/kiota-dotnet@a2800ab7, which *obsoleted*
`KiotaClientFactory.GetDefaultHandlerTypes()`, replacing it with a new
`KiotaClientFactory.GetDefaultHandlerActivatableTypes()` method which
uses an `ActivatableType` type which uses
`[DynamicallyAccessedMembers]`, a'la:

	partial class KiotaClientFactory {
	    [Obsolete("Use GetDefaultHandlerActivatableTypes")]
	    public static IList<Type> GetDefaultHandlerTypes() => …;

	    public static IList<ActivatableType> GetDefaultHandlerActivatableTypes() => [
	        new(typeof(UriReplacementHandler<UriReplacementHandlerOption>)),
	        new(typeof(RetryHandler)),
	        // …
	    ];
	    public readonly struct ActivableType {
	        public ActivatableType([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type type)
	        {
	            Type = type;
	        }
	        [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)]
	        public readonly Type type;

	        // "API Compatibility": permit implicit conversion to Type
	        public static implicit operator Type(ActivatableType type) => type.Type;
	    }
	}

There are two "problems" here:

 1. It's in a new assembly version + NuGet package version, and
 2. It's a new API, so it's not just a "update the package version
    and things work" affair.

Regardless, it *is* a fix, and *does* address the original
`InvalidOperationException`.

Update the `Microsoft.Kiota.*` NuGet packages to v1.21.0, which
contains this fix (plus many others, one imagines), and update
`ServiceCollectionExtensions.AddKiotaHandlers()` and
`ServiceCollectionExtensions.AttachKiotaHandlers()` to use the new
`KiotaClientFactory.GetDefaultHandlerActivatableTypes()` method.

[0]: https://github.com/unoplatform/uno/commit/7266db13eafdfcdd7f5569fdd195fc26658c8186