chore: .NET 9 build fixes
When building with the .NET 9 toolchain…

Fix a JSON trimmer error:

	src/Uno.Extensions.Authentication.MSAL/MsalAuthenticationProvider.cs(249,52): error IL2026:
	  Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.

Update `MsalAuthenticationProvider.cs` to use `System.Text.Json`
[Source Generators][0].

"Fix" or otherwise silence trimmer errors (?!):

	uno.extensions/src/Uno.Extensions.Hosting.UI/UnoHost.cs(105,42): error IL2026:
	  Using member 'Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, IConfiguration)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  TOptions's dependent types may have their members trimmed.
	  Ensure all required members are preserved.

In this case I'm not sure what the correct fix *is*, so use
`[UnconditionalSuppressMessage]` to silence the underlying warning.

	src/Uno.Extensions.Navigation.UI/RouteResolverDefault.cs(261,11): error IL2026:
	  Using member 'System.Reflection.Assembly.GetTypes()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
	  Types might be removed.

Add `[RequiresUnreferencedCode]` to `AssemblyExtensions.SafeGetTypes()`
and `RouteResolverDefault.LoadedTypes` (calls `.SafeGetTypes()`), then
use `[UnconditionalSuppressMessage]` to "limit the contagion" of the
`[RequiresUnreferencedCode]` on `.LoadedTypes`.

	src/Uno.Extensions.Navigation.UI/Navigators/TypeExtensions.cs(9,13): error IL2070:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'System.Type.GetConstructors()'.
	  The parameter 'type' of method 'Uno.Extensions.Navigation.Navigators.TypeExtensions.GetNavigationConstructor(Type, INavigator, IServiceProvider, out Object[])' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Do as requested: add `[DynamicallyAccessedMembers]`.
This change then impacts `ControlNavigator.Show()`, which needs to be
"propagated" to all method `override`s, e.g. `DrawerControlNavigator`.`

	src/Uno.Extensions.Navigation.UI/ServiceCollectionExtensions.cs(120,10): error IL2091:
	  'TService' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in 'Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<TService>(IServiceCollection)'.
	  The generic parameter 'TRegion' of 'Uno.Extensions.ServiceCollectionExtensions.AddRegion<TControl, TRegion>(IServiceCollection, Boolean, String)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Add `[DynamicallyAccessedMembers]` to the `TRegion` type parameter.

	src/Uno.Extensions.Navigation.UI/Navigators/ContentDialogNavigator.cs(47,16): error IL2072:
	  'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Activator.CreateInstance(Type)'.
	  The return value of method 'Uno.Extensions.Navigation.RouteInfo.RenderView.get' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Add `[DynamicallyAccessedMembers]` to `RouteInfo.RenderView`.  This
is a bit of a lie, as `RenderView` invokes `View` and is ("now"):

	partial record RouteInfo(…, Func<Type?> View, …) {
	  [DynamicallyAccessedMembers(.PublicParameterlessConstructor)]
	  public Type? RenderView => View?.Invoke();
	}

and there is no way to update the `View` parameter to assert that the
returned `Type` fulfills the requirements.  Oddly, this doesn't require
suppressing anything…

	src/Uno.Extensions.Navigation.UI/Navigators/FlyoutNavigator.cs(108,14): error IL2067:
	  'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Activator.CreateInstance(Type)'.
	  The parameter 'viewType' of method 'Uno.Extensions.Navigation.Navigators.FlyoutNavigator.DisplayFlyout(NavigationRequest, Type, Object, Boolean)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	src/Uno.Extensions.Navigation.UI/Navigators/ControlNavigator.cs(112,11): error IL2067:
	  'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Activator.CreateInstance(Type)'.
	  The parameter 'typeToCreate' of method 'Uno.Extensions.Navigation.Navigators.ControlNavigator<TControl>.CreateControlFromType(Type)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Do as requested: add `[DynamicallyAccessedMembers]`.
Fix this by using a new `TypeExtensions.CreateInstance<T>()`
extension method.  TODO: update callsites anyway?!

	src/Uno.Extensions.Navigation.UI/Controls/ActionRequestHandlerBase.cs(70,17): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Existing code allows the `PropertyInfo` to be null.  Extract out the
call and use `[UnconditionalSuppressMessage]` to squash the error.

The above were the "original" errors.  Fixing them introduced other
errors, not all of which were tracked.

When building using .NET 10 GA, one further error is reported:

	src/Uno.Extensions.Storage.UI/KeyValueStorage/KeyChainKeyValueStorage.cs(313,35): error CS8604:
	  Possible null reference argument for parameter 'valueAsString' in 'T? SerializerExtensions.FromString<T>(ISerializer serializer, string valueAsString)'.

Fix that.

---

One "intermediate oddity" that should be called out is this:

	src/Uno.Extensions.Navigation.UI/MessageDialogViewMap.cs(29,5): error IL2067:
	  'ViewModel' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Uno.Extensions.Navigation.ViewMap.ViewMap(Type, Func<Type>, Type, DataMap, Type, Object)'.
	  The parameter 'Data' of method 'Uno.Extensions.Navigation.MessageDialogViewMap.MessageDialogViewMap(String, String, Boolean, Int32, Int32, DialogAction[], Type, DataMap, Type)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Note that it's talking about the `Data` parameter.

For context:

	partial record ViewMap(
	  Type? View = null,
	  Func<Type?>? ViewSelector = null,
	  [param:   DynamicallyAccessedMembers(…)]
	  [property:DynamicallyAccessedMembers(…)]
	  Type? ViewModel = null,
	  DataMap? Data = null,
	  …
	);
	partial record MessageDialogViewMap(
	  …
	  [param:   DynamicallyAccessedMembers(…)]
	  Type? ViewModel = default,
	  DataMap? Data = default,
	  …
	) : ViewMap(
	  View: typeof(MessageDialog),
	  ViewModel: ViewModel,
	  Data: Data,
	  …
	);

@jonpryor is scratching his head, wondering how `Data` even entered
the picture.  @jonpryor assumes a (not yet reproduced) compiler bug.

The workaround is to provide *all* of the constructor parameters,
even though they're optional:

	partial record MessageDialogViewMap(
	  …
	  [param:   DynamicallyAccessedMembers(…)]
	  Type? ViewModel = default,
	  DataMap? Data = default,
	  …
	) : ViewMap(
	  View: typeof(MessageDialog),
	  ViewSelector: null,
	  ViewModel: ViewModel,
	  Data: Data,
	  …
	);

Note introduction of `ViewSelector: null` expression.
This fixes the warning.

[0]: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation