fix(trimmer): Fix trimmer warnings
Context: https://github.com/dotnet/runtime/issues/121629
Context: 56a003bab6834a77edcb7d727b8e35315059c06a
Context: c3c4c7862a911b903f1cefc4d20bc3f029ea4b26

When building with trimmer warnings enabled and turned up to 11:

	dotnet build Uno.Extensions-packageonly.slnf \
	  -p:TrimmerSingleWarn=false -p:_ExtraTrimmerArgs=--verbose \
	  -p:IsTrimmable=true -p:IsAotCompatible=true -bl

Fix the following warnings-as-errors:

	src/Uno.Extensions.Core/DependencyInjection/ServiceCollectionExtensions.cs(24,3): error IL2091:
	  'TService' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient<TService>(IServiceCollection)'.
	  The generic parameter 'TImplementation' of 'Uno.Extensions.ServiceCollectionExtensions.AddNamedSingleton<TService, TImplementation>(IServiceCollection, String)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Add the missing `[DynamicallyAccessedMembers]`.

	src/Uno.Extensions.Navigation/MappedViewMap.cs(14,6): error IL2067:
	  'ViewModel' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Uno.Extensions.Navigation.ViewMap.ViewMap(Type, Func<Type>, Type, DataMap, Type, Object)'.
	  The parameter 'ViewModel' of method 'Uno.Extensions.Navigation.MappedViewMap.MappedViewMap(Type, Func<Type>, Type, DataMap, Type, Type)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Add the missing `[DynamicallyAccessedMembers]`.

	src/Uno.Extensions.Navigation/ViewMap.cs(44,5): error IL2067:
	  'ViewModel' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Uno.Extensions.Navigation.ViewMap.ViewMap(Type, Func<Type>, Type, DataMap, Type, Object)'.
	  The parameter 'Data' of method 'Uno.Extensions.Navigation.ViewMap<TView>.ViewMap(Type, DataMap, Type, Object)' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

This is dotnet/runtime#121629.  Work around it by providing the
`ViewSelector: null` parameter.

	src/Uno.Extensions.Navigation/ViewMap.cs(66,5): error IL2087:
	  'ViewModel' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'Uno.Extensions.Navigation.ViewMap<TView>.ViewMap(Type, DataMap, Type, Object)'.
	  The generic parameter 'TViewModel' of 'Uno.Extensions.Navigation.ViewMap<TView, TViewModel>' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Add the missing `[DynamicallyAccessedMembers]`.

	src/Uno.Extensions.Navigation/RouteInfo.cs(27,29): error IL2073:
	  'Uno.Extensions.Navigation.RouteInfo.RenderView.get' method return value does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' requirements.
	  The return value of method 'System.Func<TResult>.Invoke()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

Remember 56a003ba?

> Add `[DynamicallyAccessedMembers]` to `RouteInfo.RenderView`.  This
> is a bit of a lie, as `RenderView` invokes `View` and is ("now"):
> …
> and there is no way to update the `View` parameter to assert that the
> returned `Type` fulfills the requirements.  Oddly, this doesn't require
> suppressing anything…

*Now* it needs suppressing.  We can't change the parameter type without
incurring an ABI break.

TODO: use constructor overloading?

	src/Uno.Extensions.Navigation/NavigationRequestExtensions.cs(115,30): error IL2060:
	  Call to 'System.Reflection.MethodInfo.MakeGenericMethod(params Type[])' can not be statically analyzed.
	  It's not possible to guarantee the availability of requirements of the generic method.
	src/Uno.Extensions.Navigation/NavigationRequestExtensions.cs(115,30): error IL3050:
	  Using member 'System.Reflection.MethodInfo.MakeGenericMethod(params Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  The native code for this instantiation might not be available at runtime.

This was apparently added in c3c4c786.

For now, suppress the warning.

TODO: understand why generics were added to this codepath, and
possibly *remove* them?  At a glance, the generics don't appear to be
publicly visible…

	src/Uno.Extensions.Http/ServiceCollectionExtensions.cs(117,15): error IL3050:
	  Using member 'Microsoft.Extensions.Configuration.ConfigurationBinder.Get<T>(IConfiguration)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  Binding strongly typed objects to configuration values requires generating dynamic code at runtime, for example instantiating generic types.

Add `[RequiresUnreferencedCode]` to `AddClientWithEndpoint()`.

TODO: remove the `[DynamicallyAccessedMembers]` changes to this file,
see where they came from.

	src/Uno.Extensions.Reactive/Collections/Facades/Map/LockedMemoizedConverter.cs(20,75): error IL2091:
	  'TValue' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Runtime.CompilerServices.ConditionalWeakTable<TKey, TValue>'.
	  The generic parameter 'TFrom' of 'Uno.Extensions.Conversion.LockedMemoizedConverter<TFrom, TTo>' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	…
	src/Uno.Extensions.Reactive/Collections/Facades/Map/OneWayMemoizedConverter.cs(19,75): error IL2091:
	  'TValue' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in 'System.Runtime.CompilerServices.ConditionalWeakTable<TKey, TValue>'.
	  The generic parameter 'TFrom' of 'Uno.Extensions.Conversion.OneWayMemoizedConverter<TFrom, TTo>' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.
	…

Add the missing `[DynamicallyAccessedMembers]`.

	src/Uno.Extensions.Reactive/Core/HotReload/HotReloadService.cs(69,8): error IL2075:
	  'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'.
	  The return value of method 'System.Object.GetType()' does not have matching annotations.
	  The source value must declare at least the same requirements as those declared on the target location it is assigned to.

The reflection use is required, and this is part of the
HotReload codepath, so annotate with `[RequiresUnreferencedCode]`.

	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(86,85): error IL3050:
	  Using member 'System.Text.Json.JsonSerializer.Serialize(Object, Type, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.
	src/Uno.Extensions.Serialization/SystemTextJsonSerializer.cs(104,89): error IL3050:
	  Using member 'System.Text.Json.JsonSerializer.Deserialize(String, Type, JsonSerializerOptions)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling.
	  JSON serialization and deserialization might require types that cannot be statically analyzed and might need runtime code generation.
	  Use System.Text.Json source generation for native AOT applications.

Add `[RequiresUnreferencedCode]`.