chore: update .NET version installed by azure-static-app.yml
The **Azure Static Web Apps CI/CD** stage is failing:

	Error: /usr/share/dotnet/sdk/8.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(166,5): error NETSDK1045:
	  The current .NET SDK does not support targeting .NET 9.0.
	  Either target .NET 8.0 or lower, or use a version of the .NET SDK that supports .NET 9.0.
	  Download the .NET SDK from https://aka.ms/dotnet/download

Update `azure-static-app.yml` to install .NET 9.0.308.